services:

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: hibernate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
   build:
     context: ./frontend
   container_name: frontend
   ports:
     - "3000:80"         # Maps container's port 80 (nginx) to host port 3000
   depends_on:
     - backend
   networks:
     - app-network

volumes:
  db-data:

networks:
  app-network:
