apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: somesh11/frontend:latest # Replace if building locally
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # or LoadBalancer for cloud
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Optional
